---
# ESPHome Core configuration
#
# Sets the defaults for the main core configuration of my ESPHome devices.
#
# https://esphome.io/components/esphome.html
#
name: "${name | lower | replace(' ','-')}"
friendly_name: " "
comment: "${description}"
build_path: "./.build/${id}/"
compile_process_limit: 1
# devices:
#   - id: "${id}_device"
#     name: "${name}"
