---
#
# The restart button platform allows you to restart your node remotely through
# Home Assistant.
#
# https://esphome.io/components/button/restart.html
#
id: "${id}_button_restart"
platform: restart
name: "${name} Restart"
#device_id: "${id}_device"
