---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#
platform: wifi_info
ip_address:
  name: "${name} IP Address"
  entity_category: "diagnostic"
  #device_id: "${id}_device"
ssid:
  name: "${name} Connected SSID"
  entity_category: "diagnostic"
  #device_id: "${id}_device"
bssid:
  name: "${name} Connected BSSID"
  entity_category: "diagnostic"
  #device_id: "${id}_device"
